name: depy
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core system/runtime
  - python>=3.11
  - pip
  - r-base=4.1.1
  - r-essentials

  # R dependencies (from CRAN or Bioconductor)
  - r-tidyverse
  - r-optparse
  - r-arrow
  - r-imputelcmd
  - r-statmod
  - bioconductor-biobase
  - bioconductor-limma
  - bioconductor-vsn
  - bioconductor-sva

  # Install pure Python packages via pip
  - pip:
      - pandas
      - numpy
      - matplotlib
      - pyjanitor==0.23.1
      - pandas_flavor<0.8
      - openpyxl
      - adjustText
      - jupyter
      - pytest
      - pytest-mock
      - summarizedpy
      - statsmodels
      - scikit-learn
